version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - database
  database:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '33060:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
